name: Deploy

on:
  push:
    tags:
      - v*-service-a-dev
      - v*-service-b-dev
      - v*-service-c-dev
      - v*-staging
      - v*-prod

jobs:
  
  docker:
    uses: adekurniawann/dry-workflows/.github/workflows/docker-build-push.yml@latest
    secrets:
      cr_username: ${{ secrets.CR_USERNAME }}
      cr_token: ${{ secrets.CR_TOKEN }}

  development:
    needs: docker
    if: (github.event.base_ref != 'refs/heads/production') && (endsWith(github.event.ref, 'dev'))
    uses: adekurniawann/dry-workflows/.github/workflows/swarm-deploy.yml@latest
    secrets:
      cr_username: ${{ secrets.CR_USERNAME }}
      cr_token: ${{ secrets.CR_TOKEN }}

  # staging:
  #   needs: docker
  #   if: (github.event.base_ref == 'refs/heads/staging') && (endsWith(github.event.ref, 'staging'))
  #   uses: adekurniawann/dry-workflows/.github/workflows/swarm-deploy.yml@latest
  #   secrets:
  #     cr_username: ${{ secrets.CR_USERNAME }}
  #     cr_token: ${{ secrets.CR_TOKEN }}

  # production:
  #   needs: docker
  #   if: (github.event.base_ref == 'refs/heads/production') && (endsWith(github.event.ref, 'prod'))
  #   uses: adekurniawann/dry-workflows/.github/workflows/swarm-deploy.yml@latest
  #   secrets:
  #     cr_username: ${{ secrets.CR_USERNAME }}
  #     cr_token: ${{ secrets.CR_TOKEN }}
